spring:
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tank-of-america
    username: root
    password: clean-code
  jpa:
    show-sql: false
