server:
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/User

    username: root
    password: clean-code
  jpa:
    show-sql: false
